### ISSUE TITLE
OPERA 2.2: Issues with PaDEL Calculations

### ISSUE THREAD

**Issue by dmanheim89** [kmansouri/OPERA#6]
Hello Kamel,

I've tried to download and run the new OPERA 2.2 code in MATLAB r2018a (Windows, 64 bit operating system). I've successfully downloaded and installed the 2.2 package provided on the github site. However, I keep encountering the following issues when running the source code during the PaDEL calculations:

Exception in thread "Thread-84" java.lang.ArrayIndexOutOfBoundsException: 1 
	at libpadeldescriptor.CDK_Descriptor.run(Unknown Source) 
Exception in thread "Thread-91" java.lang.ArrayIndexOutOfBoundsException: 0 
	at Jama.Matrix.<init>(Matrix.java:113) 
	at libpadeldescriptor.BurdenModifiedEigenvaluesDescriptor.calculate(Unknown Source) 
	at libpadeldescriptor.CDK_Descriptor.run(Unknown Source) 
Exception in thread "Thread-123" java.lang.ArrayIndexOutOfBoundsException: 0 
	at libpadeldescriptor.TopologicalChargeDescriptor.calculate(Unknown Source) 
	at libpadeldescriptor.CDK_Descriptor.run(Unknown Source) 
Exception in thread "Thread-124" java.lang.ArrayIndexOutOfBoundsException: -1 
	at Jama.EigenvalueDecomposition.tred2(EigenvalueDecomposition.java:173) 
	at Jama.EigenvalueDecomposition.<init>(EigenvalueDecomposition.java:884) 
	at libpadeldescriptor.TopologicalDistanceMatrixDescriptor.calculate(Unknown Source) 
	at libpadeldescriptor.CDK_Descriptor.run(Unknown Source) 
Exception in thread "Thread-99" java.lang.ArrayIndexOutOfBoundsException: -1 
	at Jama.EigenvalueDecomposition.tred2(EigenvalueDecomposition.java:173) 
	at Jama.EigenvalueDecomposition.<init>(EigenvalueDecomposition.java:884) 
	at libpadeldescriptor.DetourMatrixDescriptor.calculate(Unknown Source) 
	at libpadeldescriptor.CDK_Descriptor.run(Unknown Source) 

These errors are causing the code to produce the same physico-chemical property (i.e., VP, BCF, etc.) estimates no matter the input files used (even when I input other chemical sdf or mol files). I am not sure what the problem is here. Thank you for your assistance.

Regards,

Derek Manheim

**Comment by dmanheim89** [comment]
I resolved this issue by modifying the input files to the PaDEL software. The .sdf files downloaded from the EPA Comptox dashboard contain mol v3000 data that is not compatible with the current version of PaDEL (2.21).  One must convert the output from the dashboard to mol v2000 data in order to run this software successfully.
